version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  
  pre_build:
    commands:
      #install dependencies
      - echo installing dependencies...
      - npm install
  
  build:
    commands:
      #run build script
      - echo Build started on `date`
      - echo Building malaybiswas art website
      - npm run build

  post_build:
    commands:
      - echo Build completed at `date`

artifacts:
  #include all files required to build the application
  files:
    - "**/*"
    # reference directory where build file is located
  base-directory: "build"